Initial SQS queue + user policy
rust-lang/simpleinfra pull request #377
Opened 2024-01-04 03:10 UTC by Mark-Simulacrum

This adds a new terragrunt module for the new crates.io account(s) and puts the SQS queue and related IAM policies into the module. However, it does not yet wire up the account or try to deploy this -- I haven't connected those bits yet and getting terragrunt to cooperate with me is usually pretty finicky. Hopefully this helps as a starting point though.

Remaining steps:

* Confirm whether the IAM user + hardcoded, non-rotating access key is the best way for Heroku crates.io to access this account (at least in the short term)
* Confirm this all actually works
* Create the resources

Possibly:

* Figure out if we want a dead letter queue. This would prevent a message crates.io doesn't know how to read from blocking all other messages in the queue (since it'll constantly fail and crates.io shouldn't call DeleteMessage on it). But, it's more complexity and it's not obvious that any particular message should be any different than others. I think it's not unreasonable to punt on setting this additional infrastructure up for now.
* Figure out alarming/metrics -- maybe crates.io should self-drive this with the queue metadata API, maybe we want to wire up datadog/grafana to read from this account.

IMO if we can, let's deploy this before we actually finish wiring up s3 -- crates.io can start reading from the queue and such early that way and kick the tires.

cc https://github.com/rust-lang/simpleinfra/issues/372

r? @jdno cc @Turbo87

2024-01-08 10:59 UTC, jdno requested changes

2024-01-08 10:59 UTC, jdno commented on terragrunt/modules/crates-io-logs/main.tf
> +      values   = [data.aws_arn.account]
```suggestion
      values   = [data.aws_arn.src_bucket.account]
```

2024-01-08 10:59 UTC, jdno commented
This looks like a good starting point. 👍  Can I help you with Terragrunt somehow?

2024-01-08 13:30 UTC, Mark-Simulacrum commented
Hm, I'm not sure there's a good intermediate step, I can probably copy what I did for bors with some adjustments for the deployed-ref business...

2024-01-08 14:34 UTC, jdno approved these changes
Let me just run with this for now and make a note to go over our documentation for Terragrunt.

2024-01-09 14:57 UTC, jdno commented
I'm gonna merge this and continue in a separate branch so that we review new changes more easily.

2024-01-09 14:57 UTC, merged